### PR TITLE
Added transmitting playing song into bot status

### PR DESCRIPTION
**Pull request by piunov1998**

### CODE REVIEW

**Review by duha54rus — COMMENTED** [review]
What is a `discord.Game`?
P.S. It's _stopped_, not _stoped_.

**Comment by piunov1998** [comment]
There is `discord.CustomActivity`, but it doesn't work.

**Comment by piunov1998** [comment]
https://discordpy.readthedocs.io/en/latest/api.html?highlight=custom#game

**Review by duha54rus — APPROVED** [review]
I guess it’s fine. Hopefully won’t impact low-end machines.

**Pull request merged**
